### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by ArneBachmannDLR** [ScDor/adopt-ruff#9]
```
(311) D:\forks\HACE\autocook>adopt-ruff --code-path autocook --ruff-conf-path pyproject.toml
C:\Users\bach_ar\.conda\envs\311\Lib\site-packages\pydantic\_internal\_config.py:272: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
2024-02-22 09:35:12.526 | DEBUG    | adopt_ruff.main:_main:316 - code_path.resolve()=D:\forks\HACE\autocook\autocook
2024-02-22 09:35:12.528 | DEBUG    | adopt_ruff.main:_main:317 - ruff_conf_path=pyproject.toml
2024-02-22 09:35:12.530 | DEBUG    | adopt_ruff.main:_main:318 - include_preview=True
2024-02-22 09:35:12.538 | DEBUG    | adopt_ruff.main:_main:319 - include_sometimes_fixable=False
2024-02-22 09:35:12.540 | DEBUG    | adopt_ruff.main:_main:320 - repo_name=None
2024-02-22 09:35:12.558 | DEBUG    | adopt_ruff.main:run_ruff:31 - parsed ruff_version=0.1.14
Exception in thread Thread-3 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\bach_ar\.conda\envs\311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\bach_ar\.conda\envs\311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\bach_ar\.conda\envs\311\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "C:\Users\bach_ar\.conda\envs\311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 112446: character maps to <undefined>
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Users\bach_ar\.conda\envs\311\Lib\site-packages\adopt_ruff\main.py:322 in _main               │
│                                                                                                  │
│   319 │   logger.debug(f"{include_sometimes_fixable=}")                                          │
│   320 │   logger.debug(f"{repo_name=}")                                                          │
│   321 │                                                                                          │
│ > 322 │   rules, violations, ruff_version = run_ruff(code_path)                                  │
│   323 │   config: RuffConfig = RuffConfig.from_file(                                             │
│   324 │   │   path=ruff_conf_path or search_config_file(code_path),                              │
│   325 │   │   rules=rules,                                                                       │
│                                                                                                  │
│ ┌───────────────────────── locals ──────────────────────────┐                                    │
│ │                 code_path = WindowsPath('autocook')       │                                    │
│ │           include_preview = True                          │                                    │
│ │ include_sometimes_fixable = False                         │                                    │
│ │                 repo_name = None                          │                                    │
│ │            ruff_conf_path = WindowsPath('pyproject.toml') │                                    │
│ └───────────────────────────────────────────────────────────┘                                    │
│                                                                                                  │
│ C:\Users\bach_ar\.conda\envs\311\Lib\site-packages\adopt_ruff\main.py:40 in run_ruff             │
│                                                                                                  │
│    37 │   # Now when ruff is found, assume the following commands will run properly              │
│    38 │   rules = {                                                                              │
│    39 │   │   Rule(**value)                                                                      │
│ >  40 │   │   for value in json.loads(                                                           │
│    41 │   │   │   subprocess.run(                                                                │
│    42 │   │   │   │   ["ruff", "rule", "--all", "--output-format=json"],                         │
│    43 │   │   │   │   check=True,                                                                │
│                                                                                                  │
│ ┌──────────────── locals ────────────────┐                                                       │
│ │         path = WindowsPath('autocook') │                                                       │
│ │ ruff_version = <Version('0.1.14')>     │                                                       │
│ └────────────────────────────────────────┘                                                       │
│                                                                                                  │
│ C:\Users\bach_ar\.conda\envs\311\Lib\json\__init__.py:339 in loads                               │
│                                                                                                  │
│   336 │   │   │   │   │   │   │   │     s, 0)                                                    │
│   337 │   else:                                                                                  │
│   338 │   │   if not isinstance(s, (bytes, bytearray)):                                          │
│ > 339 │   │   │   raise TypeError(f'the JSON object must be str, bytes or bytearray, '           │
│   340 │   │   │   │   │   │   │   f'not {s.__class__.__name__}')                                 │
│   341 │   │   s = s.decode(detect_encoding(s), 'surrogatepass')                                  │
│   342                                                                                            │
│                                                                                                  │
│ ┌───────── locals ─────────┐                                                                     │
│ │               cls = None │                                                                     │
│ │                kw = {}   │                                                                     │
│ │       object_hook = None │                                                                     │
│ │ object_pairs_hook = None │                                                                     │
│ │    parse_constant = None │                                                                     │
│ │       parse_float = None │                                                                     │
│ │         parse_int = None │                                                                     │
│ │                 s = None │                                                                     │
│ └──────────────────────────┘                                                                     │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**Comment by ScDor** [comment]
Hey, thanks for opening an issue, sorry for the delay. 
If the issue still happens, please try `pip install git+https://github.com/ScDor/adopt-ruff@6abb69d3bbdd514e34132b4671e5d4c775fa8f82`, it's a custom version (from the `0x9d` branch) that logs the system encoding, and tries to explicitly use 'utf8'. Not sure about the latter, but the first one is likely to provide a hint for debugging this. 

Let me know if this solves the issue. If it doesn't please attach the `system encoding` mentioned in the log.

**Comment by ArneBachmannDLR** [comment]
No change... No matter if I use codepage 65001 (utf-8) or 1252 (Windows 8bit), I see this error:
```
(311) D:\forks\HACE\autocook>adopt-ruff --code-path autocook --ruff-conf-path pyproject.toml
C:\Users\bach_ar\.conda\envs\311\Lib\site-packages\pydantic\_internal\_config.py:284: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.7/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
C:\Users\bach_ar\.conda\envs\311\Lib\site-packages\jupyter_client\connect.py:22: DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
given by the platformdirs library.  To remove this warning and
see the appropriate new directories, set the environment variable
`JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
The use of platformdirs will be the default in `jupyter_core` v6
  from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
2024-07-01 09:57:48.135 | DEBUG    | adopt_ruff.main:_main:316 - code_path.resolve()=D:\forks\HACE\autocook\autocook
2024-07-01 09:57:48.137 | DEBUG    | adopt_ruff.main:_main:317 - ruff_conf_path=pyproject.toml
2024-07-01 09:57:48.138 | DEBUG    | adopt_ruff.main:_main:318 - include_preview=True
2024-07-01 09:57:48.140 | DEBUG    | adopt_ruff.main:_main:319 - include_sometimes_fixable=False
2024-07-01 09:57:48.144 | DEBUG    | adopt_ruff.main:_main:320 - repo_name=None
2024-07-01 09:57:48.159 | DEBUG    | adopt_ruff.main:run_ruff:31 - parsed ruff_version=0.5.0
Exception in thread Thread-3 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\bach_ar\.conda\envs\311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\bach_ar\.conda\envs\311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\bach_ar\.conda\envs\311\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "C:\Users\bach_ar\.conda\envs\311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 123226: character maps to <undefined>
```

**Comment by ScDor** [comment]
I suspect it's not the branch version (but the master one) since there's no `system encoding=` log. Please make sure it's that one.
Do you know what the system encoding is? I am not sure what the behavior is with non-utf8 ones.

**Comment by ArneBachmannDLR** [comment]
Nope. Dunno why:

```
(311) H:\>pip install -U git+https://github.com/ScDor/adopt-ruff@6abb69d3bbdd514e34132b4671e5d4c775fa8f82
C:\Users\bach_ar\.conda\envs\311\Lib\site-packages\pip\_internal\metadata\importlib\_envs.py:111: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pip._vendor.pkg_resources import find_distributions
Looking in indexes: http://pypi.org/simple, https://pypi:****@gitlab.dlr.de/api/v4/projects/8670/packages/pypi/simple
Collecting git+https://github.com/ScDor/adopt-ruff@6abb69d3bbdd514e34132b4671e5d4c775fa8f82
  Cloning https://github.com/ScDor/adopt-ruff (to revision 6abb69d3bbdd514e34132b4671e5d4c775fa8f82) to c:\users\bach_ar\appdata\local\temp\pip-req-build-_nuihdgy
  Running command git clone --filter=blob:none --quiet https://github.com/ScDor/adopt-ruff 'C:\Users\bach_ar\AppData\Local\Temp\pip-req-build-_nuihdgy'
  Running command git rev-parse -q --verify 'sha^6abb69d3bbdd514e34132b4671e5d4c775fa8f82'
  Running command git fetch -q https://github.com/ScDor/adopt-ruff 6abb69d3bbdd514e34132b4671e5d4c775fa8f82
  Running command git checkout -q 6abb69d3bbdd514e34132b4671e5d4c775fa8f82
  Resolved https://github.com/ScDor/adopt-ruff to commit 6abb69d3bbdd514e34132b4671e5d4c775fa8f82
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: loguru<0.8,>=0.7 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from adopt-ruff==0.1.0) (0.7.2)
Requirement already satisfied: mdutils<2.0,>=1.6 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from adopt-ruff==0.1.0) (1.6.0)
Requirement already satisfied: more-itertools<11.0.0,>=10.2.0 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from adopt-ruff==0.1.0) (10.2.0)
Requirement already satisfied: packaging<25.0,>=24.0 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from adopt-ruff==0.1.0) (24.1)
Requirement already satisfied: pydantic<3.0,>=2.5 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from adopt-ruff==0.1.0) (2.7.4)
Requirement already satisfied: tabulate<0.10,>=0.9 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from adopt-ruff==0.1.0) (0.9.0)
Requirement already satisfied: typer<0.13,>=0.12 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from adopt-ruff==0.1.0) (0.12.3)
Requirement already satisfied: colorama>=0.3.4 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from loguru<0.8,>=0.7->adopt-ruff==0.1.0) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from loguru<0.8,>=0.7->adopt-ruff==0.1.0) (1.1.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from pydantic<3.0,>=2.5->adopt-ruff==0.1.0) (0.6.0)
Requirement already satisfied: pydantic-core==2.18.4 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from pydantic<3.0,>=2.5->adopt-ruff==0.1.0) (2.18.4)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from pydantic<3.0,>=2.5->adopt-ruff==0.1.0) (4.9.0)
Requirement already satisfied: click>=8.0.0 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from typer<0.13,>=0.12->adopt-ruff==0.1.0) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from typer<0.13,>=0.12->adopt-ruff==0.1.0) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from typer<0.13,>=0.12->adopt-ruff==0.1.0) (13.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from rich>=10.11.0->typer<0.13,>=0.12->adopt-ruff==0.1.0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from rich>=10.11.0->typer<0.13,>=0.12->adopt-ruff==0.1.0) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\bach_ar\.conda\envs\311\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<0.13,>=0.12->adopt-ruff==0.1.0) (0.1.2)
```

And then it just seems to stop.

The adopt-ruff.exe on the path (in this environment) is still an old version, no new version was ever installed. After removing it, no new script was created.

**Comment by ScDor** [comment]
I'm not sure how to proceed here (since there's an environment issue preventing debugging) or how to assist with Windows/conda unfortunately. I'd try using the tool in WSL.

Once you're able to reproduce the issue and attach a log generated with the aforementioned branch, please reopen the issue and I'll see what I can do further.
